version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - trading-network
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - trading-network

  stock-service:
    image: ssv2612/stock-data-service:latest
    container_name: stock-service
    depends_on:
      - mongodb
      - redis
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/stockdb
      - SPRING_DATA_REDIS_HOST=redis
      - ALPHA_VANTAGE_API_KEY=HWQ0O4W9OMHM7CW6
    networks:
      - trading-network

volumes:
  mongo-data:

networks:
  trading-network:
    driver: bridge
